### PR TITLE
Weather and Cache fixes

### LINKED ISSUE #298: make the weather api robust to errors

### LINKED ISSUE #299: change hardcoded elements du to database inconsistencies

### LINKED ISSUE #302: find a solution to use multiple api keys for the weather at once

### PR DESCRIPTION
**Pull request by ziazi**
In this PR, I fixed the problems with the weather tests and api, chained multiple keys and fixed bugs resulting in the parsing of the users to put in  the cache.
PS:
The diff coverage is low because I commented game fragment tests because they're being fixed right now.

### CODE REVIEW

File: app/src/test/java/com/github/versus/ListUserConverterTest.java [hunk 1]
```diff
@@ -61,94 +61,115 @@ private static List<VersusUser> buildTestUsers() {
...
         builder.setZipCode(99);
         builder.setPreferredSports(preferredSports3);
-        VersusUser RegularGuy = builder.build();
-        return Arrays.asList(JamesBond, MohammedAli, RegularGuy);
+        VersusUser RegularGuy= builder.build();
+        return Arrays.asList(JamesBond,MohammedAli,RegularGuy);
     }
-
-    private static String buildTestString() {
-        return "007|James|Bond|NotInfiltrated|notfakemail@gmail.com|0000077777|5|London|700|MARTIALARTS, CLIMBING, CRICKET, JUDO, GOLF, SURFING, WRESTLING[u]1|Mohammad|Ali|TheGoat|IamTheDancingMaster@gmail.com|0000000001|5|Ring|1|BOXING[u]999|Regular|Guy|BasicGuy|ILoveBallSports@gmail.com|999999999|3|FootballClub|99|FOOTBALL, BASKETBALL";
```
Comment (hamzaremmal) [inline app/src/test/java/com/github/versus/ListUserConverterTest.java:69]: not sure if it's not a fake mail ;-)

**Review by hamzaremmal — APPROVED** [review]
been waiting for these tests for a long time ;-)

File: app/src/test/java/com/github/versus/ListUserConverterTest.java (hunk 1 above)
Comment (ziazi) [reply app/src/test/java/com/github/versus/ListUserConverterTest.java:69]: I was hoping someone will notice this joke 😂
